drop procedure sptest.getnames if exists]
drop procedure sptest.getname if exists]
drop procedure sptest.adder if exists]
drop table sptest.names if exists]
drop schema sptest if exists]

create schema sptest]

create procedure sptest.adder(in addend1 integer, in addend2 integer, out theSum integer)
begin atomic
  set theSum = addend1 + addend2; 
end]

create table sptest.names (
  id integer generated by default as identity not null,
  first_name varchar(20),
  last_name varchar(20),
  primary key(id)
)]

insert into sptest.names (first_name, last_name) values('Fred', 'Flintstone')]
insert into sptest.names (first_name, last_name) values('Wilma', 'Flintstone')]
insert into sptest.names (first_name, last_name) values('Barney', 'Rubble')]
insert into sptest.names (first_name, last_name) values('Betty', 'Rubble')]

-- note that these create procedure statements will fail until hsqldb 2.0.1
create procedure sptest.getname(in nameId integer)
reads sql data
dynamic result sets 1
BEGIN ATOMIC
  declare cur cursor for select * from sptest.names where id = nameId;
  open cur;
END]

create procedure sptest.getnames(in lowestId int, out totalrows integer)
reads sql data
dynamic result sets 1
BEGIN ATOMIC
  declare cur cursor for select * from sptest.names where id >= lowestId;
  select count(*) into totalrows from sptest.names where id >= lowestId;
  open cur;
END]
