drop table user if exists;
create table user(
    id int generated by default as identity,
    create_time varchar(20),
    name varchar(20),
    password varchar(20),
    phone varchar(20),
    primary key (id)
);

