drop table "awful table" if exists;

create table "awful table" (
  "CuStOmEr iD" int generated by default as identity (start with 57) not null,
  "first name" varchar(30) default 'Mabel',
  first_name varchar(30),
  firstName varchar(30),
  "last name" varchar(30),
  E_MAIL varchar(30),
  "_id1" int not null,
  "$id2" int not null,
  "id5_" int not null,
  "id6$" int not null,
  "id7$$" int not null,
  EmailAddress varchar(30),
  "from" varchar(30),
  active bit not null,
  primary key("CuStOmEr iD")
);
