create table table1 (
id int generated by default as identity (start with 11) not null,
name varchar(20)
);

create table table2 (
id int generated by default as identity (start with 22) not null,
name varchar(20)
);
