drop sequence if exists TestSequence;
drop table if exists table1;
drop table if exists table2;
drop table if exists table3;

create table table1 (
id int generated by default as identity (start with 11) not null,
name varchar(20)
);

create table table2 (
id int generated by default as identity (start with 22) not null,
name varchar(20),
name_fred varchar(25) generated always as (name || '_fred')
);

create sequence TestSequence as integer start with 33;

create table table3 (
id int not null,
name varchar(20)
);
