DROP PROCEDURE MRESULTSET;

CREATE PROCEDURE MRESULTSET(DP1 INTEGER, DP2 INTEGER, DP3 INTEGER, DP4 INTEGER)
PARAMETER STYLE JAVA
LANGUAGE JAVA
READS SQL DATA
DYNAMIC RESULT SETS 2
EXTERNAL NAME 'com.ibatis.sqlmap.proc.DerbyProcs.selectRows';