/* Generated By:JJTree: Do not edit this line. src/java/ognl\OgnlParserTreeConstants.java */

package org.apache.ibatis.ognl;

public interface OgnlParserTreeConstants {
  public int JJTVOID = 0;
  public int JJTSEQUENCE = 1;
  public int JJTASSIGN = 2;
  public int JJTTEST = 3;
  public int JJTOR = 4;
  public int JJTAND = 5;
  public int JJTBITOR = 6;
  public int JJTXOR = 7;
  public int JJTBITAND = 8;
  public int JJTEQ = 9;
  public int JJTNOTEQ = 10;
  public int JJTLESS = 11;
  public int JJTGREATER = 12;
  public int JJTLESSEQ = 13;
  public int JJTGREATEREQ = 14;
  public int JJTIN = 15;
  public int JJTNOTIN = 16;
  public int JJTSHIFTLEFT = 17;
  public int JJTSHIFTRIGHT = 18;
  public int JJTUNSIGNEDSHIFTRIGHT = 19;
  public int JJTADD = 20;
  public int JJTSUBTRACT = 21;
  public int JJTMULTIPLY = 22;
  public int JJTDIVIDE = 23;
  public int JJTREMAINDER = 24;
  public int JJTNEGATE = 25;
  public int JJTBITNEGATE = 26;
  public int JJTNOT = 27;
  public int JJTINSTANCEOF = 28;
  public int JJTCHAIN = 29;
  public int JJTEVAL = 30;
  public int JJTCONST = 31;
  public int JJTTHISVARREF = 32;
  public int JJTROOTVARREF = 33;
  public int JJTVARREF = 34;
  public int JJTLIST = 35;
  public int JJTMAP = 36;
  public int JJTKEYVALUE = 37;
  public int JJTSTATICFIELD = 38;
  public int JJTCTOR = 39;
  public int JJTPROPERTY = 40;
  public int JJTSTATICMETHOD = 41;
  public int JJTMETHOD = 42;
  public int JJTPROJECT = 43;
  public int JJTSELECT = 44;
  public int JJTSELECTFIRST = 45;
  public int JJTSELECTLAST = 46;


  public String[] jjtNodeName = {
      "void",
      "Sequence",
      "Assign",
      "Test",
      "Or",
      "And",
      "BitOr",
      "Xor",
      "BitAnd",
      "Eq",
      "NotEq",
      "Less",
      "Greater",
      "LessEq",
      "GreaterEq",
      "In",
      "NotIn",
      "ShiftLeft",
      "ShiftRight",
      "UnsignedShiftRight",
      "Add",
      "Subtract",
      "Multiply",
      "Divide",
      "Remainder",
      "Negate",
      "BitNegate",
      "Not",
      "Instanceof",
      "Chain",
      "Eval",
      "Const",
      "ThisVarRef",
      "RootVarRef",
      "VarRef",
      "List",
      "Map",
      "KeyValue",
      "StaticField",
      "Ctor",
      "Property",
      "StaticMethod",
      "Method",
      "Project",
      "Select",
      "SelectFirst",
      "SelectLast",
  };
}
