/* Generated By:JJTree&JavaCC: Do not edit this line. OgnlParserConstants.java */
package org.apache.ibatis.ognl;

public interface OgnlParserConstants {

  int EOF = 0;
  int IDENT = 64;
  int LETTER = 65;
  int DIGIT = 66;
  int DYNAMIC_SUBSCRIPT = 67;
  int ESC = 71;
  int CHAR_LITERAL = 73;
  int BACK_CHAR_ESC = 74;
  int BACK_CHAR_LITERAL = 76;
  int STRING_ESC = 77;
  int STRING_LITERAL = 79;
  int INT_LITERAL = 80;
  int FLT_LITERAL = 81;
  int DEC_FLT = 82;
  int DEC_DIGITS = 83;
  int EXPONENT = 84;
  int FLT_SUFF = 85;

  int DEFAULT = 0;
  int WithinCharLiteral = 1;
  int WithinBackCharLiteral = 2;
  int WithinStringLiteral = 3;

  String[] tokenImage = {
      "<EOF>",
      "\",\"",
      "\"=\"",
      "\"?\"",
      "\":\"",
      "\"||\"",
      "\"or\"",
      "\"&&\"",
      "\"and\"",
      "\"|\"",
      "\"bor\"",
      "\"^\"",
      "\"xor\"",
      "\"&\"",
      "\"band\"",
      "\"==\"",
      "\"eq\"",
      "\"!=\"",
      "\"neq\"",
      "\"<\"",
      "\"lt\"",
      "\">\"",
      "\"gt\"",
      "\"<=\"",
      "\"lte\"",
      "\">=\"",
      "\"gte\"",
      "\"in\"",
      "\"not\"",
      "\"<<\"",
      "\"shl\"",
      "\">>\"",
      "\"shr\"",
      "\">>>\"",
      "\"ushr\"",
      "\"+\"",
      "\"-\"",
      "\"*\"",
      "\"/\"",
      "\"%\"",
      "\"~\"",
      "\"!\"",
      "\"instanceof\"",
      "\".\"",
      "\"(\"",
      "\")\"",
      "\"true\"",
      "\"false\"",
      "\"null\"",
      "\"#this\"",
      "\"#root\"",
      "\"#\"",
      "\"[\"",
      "\"]\"",
      "\"{\"",
      "\"}\"",
      "\"@\"",
      "\"new\"",
      "\"$\"",
      "\" \"",
      "\"\\t\"",
      "\"\\f\"",
      "\"\\r\"",
      "\"\\n\"",
      "<IDENT>",
      "<LETTER>",
      "<DIGIT>",
      "<DYNAMIC_SUBSCRIPT>",
      "\"`\"",
      "\"\\\'\"",
      "\"\\\"\"",
      "<ESC>",
      "<token of kind 72>",
      "\"\\\'\"",
      "<BACK_CHAR_ESC>",
      "<token of kind 75>",
      "\"`\"",
      "<STRING_ESC>",
      "<token of kind 78>",
      "\"\\\"\"",
      "<INT_LITERAL>",
      "<FLT_LITERAL>",
      "<DEC_FLT>",
      "<DEC_DIGITS>",
      "<EXPONENT>",
      "<FLT_SUFF>",
  };

}
